name: Build Latest

on: [push]

env:
  DOTNET_SDK_VERSION: '7.0.x'

jobs:

  build-win-x64-arm64:
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true

      - run: dotnet publish BBDown -r win-x64 -c Release -o artifact-x64
      - run: dotnet publish BBDown -r win-arm64 -c Release -o artifact-arm64

      - name: Upload Artifact[win-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-x64
          path: artifact-x64\BBDown.exe

      - name: Upload Artifact[win-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-arm64
          path: artifact-arm64\BBDown.exe
  

  build-linux-x64:
    
    runs-on: ubuntu-18.04
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: sudo apt-get update
      - run: sudo apt-get install libcurl4-openssl-dev zlib1g-dev libkrb5-dev
      - run: dotnet publish BBDown -r linux-x64 -c Release -o artifact
      - run: strip artifact/BBDown
      
      - name: Upload Artifact[linux-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-x64
          path: artifact/BBDown

  build-linux-arm64:
    
    runs-on: ubuntu-18.04
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-20220312201346-b2c2436
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r linux-arm64 -c Release -p:CppCompilerAndLinker=clang-9 -p:SysRoot=/crossrootfs/arm64 -o artifact
      - run: aarch64-linux-gnu-strip artifact/BBDown
      - name: Debugging with ssh
  # You may pin to the exact commit or the version.
  # uses: lhotari/action-upterm@d23c2722bdab893785c9fbeae314cbf080645bd7
  uses: lhotari/action-upterm@v1
  with:
    # Github Token
    GITHUB_TOKEN: # optional, default is ${{ github.token }}
    # If only the public SSH keys of the user triggering the workflow should be authorized
    limit-access-to-actor: # optional, default is false
    # If only the public SSH keys of the listed GitHub users should be authorized
    limit-access-to-users: # optional, default is 
    # upterm server address (required), supported protocols are ssh, ws, or wss.
    upterm-server: # default is ssh://uptermd.upterm.dev:22
    # Content for ~/.ssh/known_hosts file on the server
    ssh-known-hosts: # optional, default is 
      - name: Upload Artifact[linux-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-arm64
          path: artifact/BBDown

  build-mac-x64:
    
    runs-on: macOS-latest
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r osx-x64 -c Release -o artifact
      - run: strip artifact/BBDown
      
      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_osx-x64
          path: artifact/BBDown
          
  build-mac-arm64:
    
    runs-on: macOS-latest
    
    steps:
      
      - uses: actions/checkout@v2
      - run: rm BBDown/Directory.Build.props
      
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r osx-arm64 -c Release -o artifact-arm64 -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true
      
      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_osx-arm64
          path: artifact-arm64/BBDown
